#!/usr/bin/env ruby

ignore 'doc', 'pkg', 'log', 'web', 'work'

desc "verify specifications"
task 'spec' do
  sh "qed"
end

# NOTE: We can't use the qed simplecov profile in the `.config.rb`
# file b/c simplecov must be loaded before the code it covers.
# So we handle it all here instead.
desc "verify specifications with coverage report"
task 'spec:cov' do
  require 'simplecov'
  SimpleCov.start do
    coverage_dir 'log/coverage'
    #add_group "Label", "lib/qed/directory"
  end
  require 'qed/cli'
  QED::Session.cli
end

file 'var/*' do
  sh 'dotruby source var'
end

file 'qed/**/*' do
  sh 'qed'
end

